### ISSUE TITLE
Pull Request Issue

### ISSUE THREAD

**Issue by jbcden** [fromPeerToPeer/captions#23]
So I've made changes to both the Ollie Charles video and the John Wiegley video. I have been trying to separate out the changes into separate pull requests but have been unable to find a way to make it work. Is it ok to submit my changes to both files as one? Suggestions?

**Comment by nelstrom** [comment]
Next time, I'm going to start by creating a branch in the `fromPeerToPeer/captions` repository. I'll ask my reviewers to create a pull request against that branch (rather than against the master branch). Hopefully, that should avoid this kind of confusion in the future. Although it will also add a bit more complexity for me and for the reviewers, so I'll have to weigh up whether or not it's worth that extra complexity!
